name: example
description: A new Flutter project.
publish_to: "none"
version: 2.2.1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter_app_badger: ^1.3.0
  flutter:
    sdk: flutter
  stream_chat_flutter: ^4.2.0
  stream_chat_persistence: ^4.1.0
  stream_chat_localizations: ^3.1.0
  flutter_local_notifications: ^9.0.0
  flutter_svg: ^1.0.3
  flutter_secure_storage: ^5.0.2
  yaml: ^3.1.0
  uuid: ^3.0.5
  streaming_shared_preferences: ^2.0.0
  lottie: ^1.2.1
  collection: ^1.15.0
  sentry_flutter: ^6.5.0

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  test: any

flutter:
  assets:
    - assets/
    - pubspec.lock
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/android_icon.png"
